//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceThatJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int categoryID { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string status { get; set; }
    }
}
